name: dto
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Generators
  freezed_annotation: ^2.4.1
  freezed: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linter
  flutter_lints: ^2.0.2

  # Generators
  flutter_gen_runner: ^5.3.1
  json_serializable: ^6.7.1
  build_runner_core: ^7.2.9
  build_runner: ^2.4.6

flutter:
  generate: true
